//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace SisEventos.ServiceReference1 {
	using System;
	using System.Runtime.Serialization;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosContato", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class DadosContato : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> eventosField;
        
        private int idField;
        
        private string nomeField;
        
        private string numeroField;
        
        private string uriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> eventos {
            get {
                return this.eventosField;
            }
            set {
                if ((object.ReferenceEquals(this.eventosField, value) != true)) {
                    this.eventosField = value;
                    this.RaisePropertyChanged("eventos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                if ((object.ReferenceEquals(this.uriField, value) != true)) {
                    this.uriField = value;
                    this.RaisePropertyChanged("uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosEvento", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class DadosEvento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dataField;
        
        private string descricaoField;
        
        private int idField;
        
        private long latitudeField;
        
        private long longitudeField;
        
        private string nomeField;
        
        private System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato> participantesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField.Equals(value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato> participantes {
            get {
                return this.participantesField;
            }
            set {
                if ((object.ReferenceEquals(this.participantesField, value) != true)) {
                    this.participantesField = value;
                    this.RaisePropertyChanged("participantes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosConvite", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class DadosConvite : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int idEventoField;
        
        private string nomeEventoField;
        
        private string numeroConvidadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEvento {
            get {
                return this.idEventoField;
            }
            set {
                if ((this.idEventoField.Equals(value) != true)) {
                    this.idEventoField = value;
                    this.RaisePropertyChanged("idEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeEvento {
            get {
                return this.nomeEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeEventoField, value) != true)) {
                    this.nomeEventoField = value;
                    this.RaisePropertyChanged("nomeEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroConvidado {
            get {
                return this.numeroConvidadoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroConvidadoField, value) != true)) {
                    this.numeroConvidadoField = value;
                    this.RaisePropertyChanged("numeroConvidado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ContatoListar", ReplyAction="http://tempuri.org/IService1/ContatoListarResponse")]
        System.IAsyncResult BeginContatoListar(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato> EndContatoListar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/EventoListar", ReplyAction="http://tempuri.org/IService1/EventoListarResponse")]
        System.IAsyncResult BeginEventoListar(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> EndEventoListar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ContatoAbrir", ReplyAction="http://tempuri.org/IService1/ContatoAbrirResponse")]
        System.IAsyncResult BeginContatoAbrir(string numero, System.AsyncCallback callback, object asyncState);
        
        SisEventos.ServiceReference1.DadosContato EndContatoAbrir(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ContatoAdicionar", ReplyAction="http://tempuri.org/IService1/ContatoAdicionarResponse")]
        System.IAsyncResult BeginContatoAdicionar(string nome, string numero, string uri, System.AsyncCallback callback, object asyncState);
        
        void EndContatoAdicionar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ContatoAtualizar", ReplyAction="http://tempuri.org/IService1/ContatoAtualizarResponse")]
        System.IAsyncResult BeginContatoAtualizar(string nome, string numero, string uri, System.AsyncCallback callback, object asyncState);
        
        void EndContatoAtualizar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ContatoEventos", ReplyAction="http://tempuri.org/IService1/ContatoEventosResponse")]
        System.IAsyncResult BeginContatoEventos(string numero, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> EndContatoEventos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/EventoAbrir", ReplyAction="http://tempuri.org/IService1/EventoAbrirResponse")]
        System.IAsyncResult BeginEventoAbrir(int id, System.AsyncCallback callback, object asyncState);
        
        SisEventos.ServiceReference1.DadosEvento EndEventoAbrir(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/EventoAdicionar", ReplyAction="http://tempuri.org/IService1/EventoAdicionarResponse")]
        System.IAsyncResult BeginEventoAdicionar(string nome, string descricao, System.DateTime data, string numero_responsavel, long latitude, long longitude, System.AsyncCallback callback, object asyncState);
        
        void EndEventoAdicionar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/EventoAtualizar", ReplyAction="http://tempuri.org/IService1/EventoAtualizarResponse")]
        System.IAsyncResult BeginEventoAtualizar(int evento_id, string nome, string descricao, System.DateTime data, long latitude, long longitude, System.AsyncCallback callback, object asyncState);
        
        void EndEventoAtualizar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/EventoDelete", ReplyAction="http://tempuri.org/IService1/EventoDeleteResponse")]
        System.IAsyncResult BeginEventoDelete(int evento_id, System.AsyncCallback callback, object asyncState);
        
        void EndEventoDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/EventoConvidarParticipante", ReplyAction="http://tempuri.org/IService1/EventoConvidarParticipanteResponse")]
        System.IAsyncResult BeginEventoConvidarParticipante(int evento_id, string numero_participante, System.AsyncCallback callback, object asyncState);
        
        void EndEventoConvidarParticipante(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/EventoRemoverParticipante", ReplyAction="http://tempuri.org/IService1/EventoRemoverParticipanteResponse")]
        System.IAsyncResult BeginEventoRemoverParticipante(int evento_id, string numero_participante, System.AsyncCallback callback, object asyncState);
        
        void EndEventoRemoverParticipante(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ConviteAbrir", ReplyAction="http://tempuri.org/IService1/ConviteAbrirResponse")]
        System.IAsyncResult BeginConviteAbrir(int id, System.AsyncCallback callback, object asyncState);
        
        SisEventos.ServiceReference1.DadosEvento EndConviteAbrir(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ConviteListar", ReplyAction="http://tempuri.org/IService1/ConviteListarResponse")]
        System.IAsyncResult BeginConviteListar(string numeroContato, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosConvite> EndConviteListar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ConviteAceitar", ReplyAction="http://tempuri.org/IService1/ConviteAceitarResponse")]
        System.IAsyncResult BeginConviteAceitar(int idConvite, System.AsyncCallback callback, object asyncState);
        
        void EndConviteAceitar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ConviteRecusar", ReplyAction="http://tempuri.org/IService1/ConviteRecusarResponse")]
        System.IAsyncResult BeginConviteRecusar(int idConvite, System.AsyncCallback callback, object asyncState);
        
        void EndConviteRecusar(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SisEventos.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContatoListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ContatoListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventoListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EventoListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContatoAbrirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ContatoAbrirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SisEventos.ServiceReference1.DadosContato Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SisEventos.ServiceReference1.DadosContato)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContatoEventosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ContatoEventosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventoAbrirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EventoAbrirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SisEventos.ServiceReference1.DadosEvento Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SisEventos.ServiceReference1.DadosEvento)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConviteAbrirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConviteAbrirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SisEventos.ServiceReference1.DadosEvento Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SisEventos.ServiceReference1.DadosEvento)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConviteListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConviteListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosConvite> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosConvite>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SisEventos.ServiceReference1.IService1>, SisEventos.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginContatoListarDelegate;
        
        private EndOperationDelegate onEndContatoListarDelegate;
        
        private System.Threading.SendOrPostCallback onContatoListarCompletedDelegate;
        
        private BeginOperationDelegate onBeginEventoListarDelegate;
        
        private EndOperationDelegate onEndEventoListarDelegate;
        
        private System.Threading.SendOrPostCallback onEventoListarCompletedDelegate;
        
        private BeginOperationDelegate onBeginContatoAbrirDelegate;
        
        private EndOperationDelegate onEndContatoAbrirDelegate;
        
        private System.Threading.SendOrPostCallback onContatoAbrirCompletedDelegate;
        
        private BeginOperationDelegate onBeginContatoAdicionarDelegate;
        
        private EndOperationDelegate onEndContatoAdicionarDelegate;
        
        private System.Threading.SendOrPostCallback onContatoAdicionarCompletedDelegate;
        
        private BeginOperationDelegate onBeginContatoAtualizarDelegate;
        
        private EndOperationDelegate onEndContatoAtualizarDelegate;
        
        private System.Threading.SendOrPostCallback onContatoAtualizarCompletedDelegate;
        
        private BeginOperationDelegate onBeginContatoEventosDelegate;
        
        private EndOperationDelegate onEndContatoEventosDelegate;
        
        private System.Threading.SendOrPostCallback onContatoEventosCompletedDelegate;
        
        private BeginOperationDelegate onBeginEventoAbrirDelegate;
        
        private EndOperationDelegate onEndEventoAbrirDelegate;
        
        private System.Threading.SendOrPostCallback onEventoAbrirCompletedDelegate;
        
        private BeginOperationDelegate onBeginEventoAdicionarDelegate;
        
        private EndOperationDelegate onEndEventoAdicionarDelegate;
        
        private System.Threading.SendOrPostCallback onEventoAdicionarCompletedDelegate;
        
        private BeginOperationDelegate onBeginEventoAtualizarDelegate;
        
        private EndOperationDelegate onEndEventoAtualizarDelegate;
        
        private System.Threading.SendOrPostCallback onEventoAtualizarCompletedDelegate;
        
        private BeginOperationDelegate onBeginEventoDeleteDelegate;
        
        private EndOperationDelegate onEndEventoDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onEventoDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginEventoConvidarParticipanteDelegate;
        
        private EndOperationDelegate onEndEventoConvidarParticipanteDelegate;
        
        private System.Threading.SendOrPostCallback onEventoConvidarParticipanteCompletedDelegate;
        
        private BeginOperationDelegate onBeginEventoRemoverParticipanteDelegate;
        
        private EndOperationDelegate onEndEventoRemoverParticipanteDelegate;
        
        private System.Threading.SendOrPostCallback onEventoRemoverParticipanteCompletedDelegate;
        
        private BeginOperationDelegate onBeginConviteAbrirDelegate;
        
        private EndOperationDelegate onEndConviteAbrirDelegate;
        
        private System.Threading.SendOrPostCallback onConviteAbrirCompletedDelegate;
        
        private BeginOperationDelegate onBeginConviteListarDelegate;
        
        private EndOperationDelegate onEndConviteListarDelegate;
        
        private System.Threading.SendOrPostCallback onConviteListarCompletedDelegate;
        
        private BeginOperationDelegate onBeginConviteAceitarDelegate;
        
        private EndOperationDelegate onEndConviteAceitarDelegate;
        
        private System.Threading.SendOrPostCallback onConviteAceitarCompletedDelegate;
        
        private BeginOperationDelegate onBeginConviteRecusarDelegate;
        
        private EndOperationDelegate onEndConviteRecusarDelegate;
        
        private System.Threading.SendOrPostCallback onConviteRecusarCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<ContatoListarCompletedEventArgs> ContatoListarCompleted;
        
        public event System.EventHandler<EventoListarCompletedEventArgs> EventoListarCompleted;
        
        public event System.EventHandler<ContatoAbrirCompletedEventArgs> ContatoAbrirCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ContatoAdicionarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ContatoAtualizarCompleted;
        
        public event System.EventHandler<ContatoEventosCompletedEventArgs> ContatoEventosCompleted;
        
        public event System.EventHandler<EventoAbrirCompletedEventArgs> EventoAbrirCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EventoAdicionarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EventoAtualizarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EventoDeleteCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EventoConvidarParticipanteCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EventoRemoverParticipanteCompleted;
        
        public event System.EventHandler<ConviteAbrirCompletedEventArgs> ConviteAbrirCompleted;
        
        public event System.EventHandler<ConviteListarCompletedEventArgs> ConviteListarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ConviteAceitarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ConviteRecusarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginContatoListar(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginContatoListar(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato> SisEventos.ServiceReference1.IService1.EndContatoListar(System.IAsyncResult result) {
            return base.Channel.EndContatoListar(result);
        }
        
        private System.IAsyncResult OnBeginContatoListar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginContatoListar(callback, asyncState);
        }
        
        private object[] OnEndContatoListar(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato> retVal = ((SisEventos.ServiceReference1.IService1)(this)).EndContatoListar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnContatoListarCompleted(object state) {
            if ((this.ContatoListarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ContatoListarCompleted(this, new ContatoListarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ContatoListarAsync() {
            this.ContatoListarAsync(null);
        }
        
        public void ContatoListarAsync(object userState) {
            if ((this.onBeginContatoListarDelegate == null)) {
                this.onBeginContatoListarDelegate = new BeginOperationDelegate(this.OnBeginContatoListar);
            }
            if ((this.onEndContatoListarDelegate == null)) {
                this.onEndContatoListarDelegate = new EndOperationDelegate(this.OnEndContatoListar);
            }
            if ((this.onContatoListarCompletedDelegate == null)) {
                this.onContatoListarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnContatoListarCompleted);
            }
            base.InvokeAsync(this.onBeginContatoListarDelegate, null, this.onEndContatoListarDelegate, this.onContatoListarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginEventoListar(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEventoListar(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> SisEventos.ServiceReference1.IService1.EndEventoListar(System.IAsyncResult result) {
            return base.Channel.EndEventoListar(result);
        }
        
        private System.IAsyncResult OnBeginEventoListar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginEventoListar(callback, asyncState);
        }
        
        private object[] OnEndEventoListar(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> retVal = ((SisEventos.ServiceReference1.IService1)(this)).EndEventoListar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEventoListarCompleted(object state) {
            if ((this.EventoListarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EventoListarCompleted(this, new EventoListarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EventoListarAsync() {
            this.EventoListarAsync(null);
        }
        
        public void EventoListarAsync(object userState) {
            if ((this.onBeginEventoListarDelegate == null)) {
                this.onBeginEventoListarDelegate = new BeginOperationDelegate(this.OnBeginEventoListar);
            }
            if ((this.onEndEventoListarDelegate == null)) {
                this.onEndEventoListarDelegate = new EndOperationDelegate(this.OnEndEventoListar);
            }
            if ((this.onEventoListarCompletedDelegate == null)) {
                this.onEventoListarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEventoListarCompleted);
            }
            base.InvokeAsync(this.onBeginEventoListarDelegate, null, this.onEndEventoListarDelegate, this.onEventoListarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginContatoAbrir(string numero, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginContatoAbrir(numero, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisEventos.ServiceReference1.DadosContato SisEventos.ServiceReference1.IService1.EndContatoAbrir(System.IAsyncResult result) {
            return base.Channel.EndContatoAbrir(result);
        }
        
        private System.IAsyncResult OnBeginContatoAbrir(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string numero = ((string)(inValues[0]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginContatoAbrir(numero, callback, asyncState);
        }
        
        private object[] OnEndContatoAbrir(System.IAsyncResult result) {
            SisEventos.ServiceReference1.DadosContato retVal = ((SisEventos.ServiceReference1.IService1)(this)).EndContatoAbrir(result);
            return new object[] {
                    retVal};
        }
        
        private void OnContatoAbrirCompleted(object state) {
            if ((this.ContatoAbrirCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ContatoAbrirCompleted(this, new ContatoAbrirCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ContatoAbrirAsync(string numero) {
            this.ContatoAbrirAsync(numero, null);
        }
        
        public void ContatoAbrirAsync(string numero, object userState) {
            if ((this.onBeginContatoAbrirDelegate == null)) {
                this.onBeginContatoAbrirDelegate = new BeginOperationDelegate(this.OnBeginContatoAbrir);
            }
            if ((this.onEndContatoAbrirDelegate == null)) {
                this.onEndContatoAbrirDelegate = new EndOperationDelegate(this.OnEndContatoAbrir);
            }
            if ((this.onContatoAbrirCompletedDelegate == null)) {
                this.onContatoAbrirCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnContatoAbrirCompleted);
            }
            base.InvokeAsync(this.onBeginContatoAbrirDelegate, new object[] {
                        numero}, this.onEndContatoAbrirDelegate, this.onContatoAbrirCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginContatoAdicionar(string nome, string numero, string uri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginContatoAdicionar(nome, numero, uri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SisEventos.ServiceReference1.IService1.EndContatoAdicionar(System.IAsyncResult result) {
            base.Channel.EndContatoAdicionar(result);
        }
        
        private System.IAsyncResult OnBeginContatoAdicionar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nome = ((string)(inValues[0]));
            string numero = ((string)(inValues[1]));
            string uri = ((string)(inValues[2]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginContatoAdicionar(nome, numero, uri, callback, asyncState);
        }
        
        private object[] OnEndContatoAdicionar(System.IAsyncResult result) {
            ((SisEventos.ServiceReference1.IService1)(this)).EndContatoAdicionar(result);
            return null;
        }
        
        private void OnContatoAdicionarCompleted(object state) {
            if ((this.ContatoAdicionarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ContatoAdicionarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ContatoAdicionarAsync(string nome, string numero, string uri) {
            this.ContatoAdicionarAsync(nome, numero, uri, null);
        }
        
        public void ContatoAdicionarAsync(string nome, string numero, string uri, object userState) {
            if ((this.onBeginContatoAdicionarDelegate == null)) {
                this.onBeginContatoAdicionarDelegate = new BeginOperationDelegate(this.OnBeginContatoAdicionar);
            }
            if ((this.onEndContatoAdicionarDelegate == null)) {
                this.onEndContatoAdicionarDelegate = new EndOperationDelegate(this.OnEndContatoAdicionar);
            }
            if ((this.onContatoAdicionarCompletedDelegate == null)) {
                this.onContatoAdicionarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnContatoAdicionarCompleted);
            }
            base.InvokeAsync(this.onBeginContatoAdicionarDelegate, new object[] {
                        nome,
                        numero,
                        uri}, this.onEndContatoAdicionarDelegate, this.onContatoAdicionarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginContatoAtualizar(string nome, string numero, string uri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginContatoAtualizar(nome, numero, uri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SisEventos.ServiceReference1.IService1.EndContatoAtualizar(System.IAsyncResult result) {
            base.Channel.EndContatoAtualizar(result);
        }
        
        private System.IAsyncResult OnBeginContatoAtualizar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nome = ((string)(inValues[0]));
            string numero = ((string)(inValues[1]));
            string uri = ((string)(inValues[2]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginContatoAtualizar(nome, numero, uri, callback, asyncState);
        }
        
        private object[] OnEndContatoAtualizar(System.IAsyncResult result) {
            ((SisEventos.ServiceReference1.IService1)(this)).EndContatoAtualizar(result);
            return null;
        }
        
        private void OnContatoAtualizarCompleted(object state) {
            if ((this.ContatoAtualizarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ContatoAtualizarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ContatoAtualizarAsync(string nome, string numero, string uri) {
            this.ContatoAtualizarAsync(nome, numero, uri, null);
        }
        
        public void ContatoAtualizarAsync(string nome, string numero, string uri, object userState) {
            if ((this.onBeginContatoAtualizarDelegate == null)) {
                this.onBeginContatoAtualizarDelegate = new BeginOperationDelegate(this.OnBeginContatoAtualizar);
            }
            if ((this.onEndContatoAtualizarDelegate == null)) {
                this.onEndContatoAtualizarDelegate = new EndOperationDelegate(this.OnEndContatoAtualizar);
            }
            if ((this.onContatoAtualizarCompletedDelegate == null)) {
                this.onContatoAtualizarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnContatoAtualizarCompleted);
            }
            base.InvokeAsync(this.onBeginContatoAtualizarDelegate, new object[] {
                        nome,
                        numero,
                        uri}, this.onEndContatoAtualizarDelegate, this.onContatoAtualizarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginContatoEventos(string numero, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginContatoEventos(numero, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> SisEventos.ServiceReference1.IService1.EndContatoEventos(System.IAsyncResult result) {
            return base.Channel.EndContatoEventos(result);
        }
        
        private System.IAsyncResult OnBeginContatoEventos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string numero = ((string)(inValues[0]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginContatoEventos(numero, callback, asyncState);
        }
        
        private object[] OnEndContatoEventos(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> retVal = ((SisEventos.ServiceReference1.IService1)(this)).EndContatoEventos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnContatoEventosCompleted(object state) {
            if ((this.ContatoEventosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ContatoEventosCompleted(this, new ContatoEventosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ContatoEventosAsync(string numero) {
            this.ContatoEventosAsync(numero, null);
        }
        
        public void ContatoEventosAsync(string numero, object userState) {
            if ((this.onBeginContatoEventosDelegate == null)) {
                this.onBeginContatoEventosDelegate = new BeginOperationDelegate(this.OnBeginContatoEventos);
            }
            if ((this.onEndContatoEventosDelegate == null)) {
                this.onEndContatoEventosDelegate = new EndOperationDelegate(this.OnEndContatoEventos);
            }
            if ((this.onContatoEventosCompletedDelegate == null)) {
                this.onContatoEventosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnContatoEventosCompleted);
            }
            base.InvokeAsync(this.onBeginContatoEventosDelegate, new object[] {
                        numero}, this.onEndContatoEventosDelegate, this.onContatoEventosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginEventoAbrir(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEventoAbrir(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisEventos.ServiceReference1.DadosEvento SisEventos.ServiceReference1.IService1.EndEventoAbrir(System.IAsyncResult result) {
            return base.Channel.EndEventoAbrir(result);
        }
        
        private System.IAsyncResult OnBeginEventoAbrir(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginEventoAbrir(id, callback, asyncState);
        }
        
        private object[] OnEndEventoAbrir(System.IAsyncResult result) {
            SisEventos.ServiceReference1.DadosEvento retVal = ((SisEventos.ServiceReference1.IService1)(this)).EndEventoAbrir(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEventoAbrirCompleted(object state) {
            if ((this.EventoAbrirCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EventoAbrirCompleted(this, new EventoAbrirCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EventoAbrirAsync(int id) {
            this.EventoAbrirAsync(id, null);
        }
        
        public void EventoAbrirAsync(int id, object userState) {
            if ((this.onBeginEventoAbrirDelegate == null)) {
                this.onBeginEventoAbrirDelegate = new BeginOperationDelegate(this.OnBeginEventoAbrir);
            }
            if ((this.onEndEventoAbrirDelegate == null)) {
                this.onEndEventoAbrirDelegate = new EndOperationDelegate(this.OnEndEventoAbrir);
            }
            if ((this.onEventoAbrirCompletedDelegate == null)) {
                this.onEventoAbrirCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEventoAbrirCompleted);
            }
            base.InvokeAsync(this.onBeginEventoAbrirDelegate, new object[] {
                        id}, this.onEndEventoAbrirDelegate, this.onEventoAbrirCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginEventoAdicionar(string nome, string descricao, System.DateTime data, string numero_responsavel, long latitude, long longitude, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEventoAdicionar(nome, descricao, data, numero_responsavel, latitude, longitude, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SisEventos.ServiceReference1.IService1.EndEventoAdicionar(System.IAsyncResult result) {
            base.Channel.EndEventoAdicionar(result);
        }
        
        private System.IAsyncResult OnBeginEventoAdicionar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nome = ((string)(inValues[0]));
            string descricao = ((string)(inValues[1]));
            System.DateTime data = ((System.DateTime)(inValues[2]));
            string numero_responsavel = ((string)(inValues[3]));
            long latitude = ((long)(inValues[4]));
            long longitude = ((long)(inValues[5]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginEventoAdicionar(nome, descricao, data, numero_responsavel, latitude, longitude, callback, asyncState);
        }
        
        private object[] OnEndEventoAdicionar(System.IAsyncResult result) {
            ((SisEventos.ServiceReference1.IService1)(this)).EndEventoAdicionar(result);
            return null;
        }
        
        private void OnEventoAdicionarCompleted(object state) {
            if ((this.EventoAdicionarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EventoAdicionarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EventoAdicionarAsync(string nome, string descricao, System.DateTime data, string numero_responsavel, long latitude, long longitude) {
            this.EventoAdicionarAsync(nome, descricao, data, numero_responsavel, latitude, longitude, null);
        }
        
        public void EventoAdicionarAsync(string nome, string descricao, System.DateTime data, string numero_responsavel, long latitude, long longitude, object userState) {
            if ((this.onBeginEventoAdicionarDelegate == null)) {
                this.onBeginEventoAdicionarDelegate = new BeginOperationDelegate(this.OnBeginEventoAdicionar);
            }
            if ((this.onEndEventoAdicionarDelegate == null)) {
                this.onEndEventoAdicionarDelegate = new EndOperationDelegate(this.OnEndEventoAdicionar);
            }
            if ((this.onEventoAdicionarCompletedDelegate == null)) {
                this.onEventoAdicionarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEventoAdicionarCompleted);
            }
            base.InvokeAsync(this.onBeginEventoAdicionarDelegate, new object[] {
                        nome,
                        descricao,
                        data,
                        numero_responsavel,
                        latitude,
                        longitude}, this.onEndEventoAdicionarDelegate, this.onEventoAdicionarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginEventoAtualizar(int evento_id, string nome, string descricao, System.DateTime data, long latitude, long longitude, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEventoAtualizar(evento_id, nome, descricao, data, latitude, longitude, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SisEventos.ServiceReference1.IService1.EndEventoAtualizar(System.IAsyncResult result) {
            base.Channel.EndEventoAtualizar(result);
        }
        
        private System.IAsyncResult OnBeginEventoAtualizar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int evento_id = ((int)(inValues[0]));
            string nome = ((string)(inValues[1]));
            string descricao = ((string)(inValues[2]));
            System.DateTime data = ((System.DateTime)(inValues[3]));
            long latitude = ((long)(inValues[4]));
            long longitude = ((long)(inValues[5]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginEventoAtualizar(evento_id, nome, descricao, data, latitude, longitude, callback, asyncState);
        }
        
        private object[] OnEndEventoAtualizar(System.IAsyncResult result) {
            ((SisEventos.ServiceReference1.IService1)(this)).EndEventoAtualizar(result);
            return null;
        }
        
        private void OnEventoAtualizarCompleted(object state) {
            if ((this.EventoAtualizarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EventoAtualizarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EventoAtualizarAsync(int evento_id, string nome, string descricao, System.DateTime data, long latitude, long longitude) {
            this.EventoAtualizarAsync(evento_id, nome, descricao, data, latitude, longitude, null);
        }
        
        public void EventoAtualizarAsync(int evento_id, string nome, string descricao, System.DateTime data, long latitude, long longitude, object userState) {
            if ((this.onBeginEventoAtualizarDelegate == null)) {
                this.onBeginEventoAtualizarDelegate = new BeginOperationDelegate(this.OnBeginEventoAtualizar);
            }
            if ((this.onEndEventoAtualizarDelegate == null)) {
                this.onEndEventoAtualizarDelegate = new EndOperationDelegate(this.OnEndEventoAtualizar);
            }
            if ((this.onEventoAtualizarCompletedDelegate == null)) {
                this.onEventoAtualizarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEventoAtualizarCompleted);
            }
            base.InvokeAsync(this.onBeginEventoAtualizarDelegate, new object[] {
                        evento_id,
                        nome,
                        descricao,
                        data,
                        latitude,
                        longitude}, this.onEndEventoAtualizarDelegate, this.onEventoAtualizarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginEventoDelete(int evento_id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEventoDelete(evento_id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SisEventos.ServiceReference1.IService1.EndEventoDelete(System.IAsyncResult result) {
            base.Channel.EndEventoDelete(result);
        }
        
        private System.IAsyncResult OnBeginEventoDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int evento_id = ((int)(inValues[0]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginEventoDelete(evento_id, callback, asyncState);
        }
        
        private object[] OnEndEventoDelete(System.IAsyncResult result) {
            ((SisEventos.ServiceReference1.IService1)(this)).EndEventoDelete(result);
            return null;
        }
        
        private void OnEventoDeleteCompleted(object state) {
            if ((this.EventoDeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EventoDeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EventoDeleteAsync(int evento_id) {
            this.EventoDeleteAsync(evento_id, null);
        }
        
        public void EventoDeleteAsync(int evento_id, object userState) {
            if ((this.onBeginEventoDeleteDelegate == null)) {
                this.onBeginEventoDeleteDelegate = new BeginOperationDelegate(this.OnBeginEventoDelete);
            }
            if ((this.onEndEventoDeleteDelegate == null)) {
                this.onEndEventoDeleteDelegate = new EndOperationDelegate(this.OnEndEventoDelete);
            }
            if ((this.onEventoDeleteCompletedDelegate == null)) {
                this.onEventoDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEventoDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginEventoDeleteDelegate, new object[] {
                        evento_id}, this.onEndEventoDeleteDelegate, this.onEventoDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginEventoConvidarParticipante(int evento_id, string numero_participante, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEventoConvidarParticipante(evento_id, numero_participante, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SisEventos.ServiceReference1.IService1.EndEventoConvidarParticipante(System.IAsyncResult result) {
            base.Channel.EndEventoConvidarParticipante(result);
        }
        
        private System.IAsyncResult OnBeginEventoConvidarParticipante(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int evento_id = ((int)(inValues[0]));
            string numero_participante = ((string)(inValues[1]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginEventoConvidarParticipante(evento_id, numero_participante, callback, asyncState);
        }
        
        private object[] OnEndEventoConvidarParticipante(System.IAsyncResult result) {
            ((SisEventos.ServiceReference1.IService1)(this)).EndEventoConvidarParticipante(result);
            return null;
        }
        
        private void OnEventoConvidarParticipanteCompleted(object state) {
            if ((this.EventoConvidarParticipanteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EventoConvidarParticipanteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EventoConvidarParticipanteAsync(int evento_id, string numero_participante) {
            this.EventoConvidarParticipanteAsync(evento_id, numero_participante, null);
        }
        
        public void EventoConvidarParticipanteAsync(int evento_id, string numero_participante, object userState) {
            if ((this.onBeginEventoConvidarParticipanteDelegate == null)) {
                this.onBeginEventoConvidarParticipanteDelegate = new BeginOperationDelegate(this.OnBeginEventoConvidarParticipante);
            }
            if ((this.onEndEventoConvidarParticipanteDelegate == null)) {
                this.onEndEventoConvidarParticipanteDelegate = new EndOperationDelegate(this.OnEndEventoConvidarParticipante);
            }
            if ((this.onEventoConvidarParticipanteCompletedDelegate == null)) {
                this.onEventoConvidarParticipanteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEventoConvidarParticipanteCompleted);
            }
            base.InvokeAsync(this.onBeginEventoConvidarParticipanteDelegate, new object[] {
                        evento_id,
                        numero_participante}, this.onEndEventoConvidarParticipanteDelegate, this.onEventoConvidarParticipanteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginEventoRemoverParticipante(int evento_id, string numero_participante, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEventoRemoverParticipante(evento_id, numero_participante, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SisEventos.ServiceReference1.IService1.EndEventoRemoverParticipante(System.IAsyncResult result) {
            base.Channel.EndEventoRemoverParticipante(result);
        }
        
        private System.IAsyncResult OnBeginEventoRemoverParticipante(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int evento_id = ((int)(inValues[0]));
            string numero_participante = ((string)(inValues[1]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginEventoRemoverParticipante(evento_id, numero_participante, callback, asyncState);
        }
        
        private object[] OnEndEventoRemoverParticipante(System.IAsyncResult result) {
            ((SisEventos.ServiceReference1.IService1)(this)).EndEventoRemoverParticipante(result);
            return null;
        }
        
        private void OnEventoRemoverParticipanteCompleted(object state) {
            if ((this.EventoRemoverParticipanteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EventoRemoverParticipanteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EventoRemoverParticipanteAsync(int evento_id, string numero_participante) {
            this.EventoRemoverParticipanteAsync(evento_id, numero_participante, null);
        }
        
        public void EventoRemoverParticipanteAsync(int evento_id, string numero_participante, object userState) {
            if ((this.onBeginEventoRemoverParticipanteDelegate == null)) {
                this.onBeginEventoRemoverParticipanteDelegate = new BeginOperationDelegate(this.OnBeginEventoRemoverParticipante);
            }
            if ((this.onEndEventoRemoverParticipanteDelegate == null)) {
                this.onEndEventoRemoverParticipanteDelegate = new EndOperationDelegate(this.OnEndEventoRemoverParticipante);
            }
            if ((this.onEventoRemoverParticipanteCompletedDelegate == null)) {
                this.onEventoRemoverParticipanteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEventoRemoverParticipanteCompleted);
            }
            base.InvokeAsync(this.onBeginEventoRemoverParticipanteDelegate, new object[] {
                        evento_id,
                        numero_participante}, this.onEndEventoRemoverParticipanteDelegate, this.onEventoRemoverParticipanteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginConviteAbrir(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConviteAbrir(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisEventos.ServiceReference1.DadosEvento SisEventos.ServiceReference1.IService1.EndConviteAbrir(System.IAsyncResult result) {
            return base.Channel.EndConviteAbrir(result);
        }
        
        private System.IAsyncResult OnBeginConviteAbrir(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginConviteAbrir(id, callback, asyncState);
        }
        
        private object[] OnEndConviteAbrir(System.IAsyncResult result) {
            SisEventos.ServiceReference1.DadosEvento retVal = ((SisEventos.ServiceReference1.IService1)(this)).EndConviteAbrir(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConviteAbrirCompleted(object state) {
            if ((this.ConviteAbrirCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConviteAbrirCompleted(this, new ConviteAbrirCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConviteAbrirAsync(int id) {
            this.ConviteAbrirAsync(id, null);
        }
        
        public void ConviteAbrirAsync(int id, object userState) {
            if ((this.onBeginConviteAbrirDelegate == null)) {
                this.onBeginConviteAbrirDelegate = new BeginOperationDelegate(this.OnBeginConviteAbrir);
            }
            if ((this.onEndConviteAbrirDelegate == null)) {
                this.onEndConviteAbrirDelegate = new EndOperationDelegate(this.OnEndConviteAbrir);
            }
            if ((this.onConviteAbrirCompletedDelegate == null)) {
                this.onConviteAbrirCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConviteAbrirCompleted);
            }
            base.InvokeAsync(this.onBeginConviteAbrirDelegate, new object[] {
                        id}, this.onEndConviteAbrirDelegate, this.onConviteAbrirCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginConviteListar(string numeroContato, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConviteListar(numeroContato, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosConvite> SisEventos.ServiceReference1.IService1.EndConviteListar(System.IAsyncResult result) {
            return base.Channel.EndConviteListar(result);
        }
        
        private System.IAsyncResult OnBeginConviteListar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string numeroContato = ((string)(inValues[0]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginConviteListar(numeroContato, callback, asyncState);
        }
        
        private object[] OnEndConviteListar(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosConvite> retVal = ((SisEventos.ServiceReference1.IService1)(this)).EndConviteListar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConviteListarCompleted(object state) {
            if ((this.ConviteListarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConviteListarCompleted(this, new ConviteListarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConviteListarAsync(string numeroContato) {
            this.ConviteListarAsync(numeroContato, null);
        }
        
        public void ConviteListarAsync(string numeroContato, object userState) {
            if ((this.onBeginConviteListarDelegate == null)) {
                this.onBeginConviteListarDelegate = new BeginOperationDelegate(this.OnBeginConviteListar);
            }
            if ((this.onEndConviteListarDelegate == null)) {
                this.onEndConviteListarDelegate = new EndOperationDelegate(this.OnEndConviteListar);
            }
            if ((this.onConviteListarCompletedDelegate == null)) {
                this.onConviteListarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConviteListarCompleted);
            }
            base.InvokeAsync(this.onBeginConviteListarDelegate, new object[] {
                        numeroContato}, this.onEndConviteListarDelegate, this.onConviteListarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginConviteAceitar(int idConvite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConviteAceitar(idConvite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SisEventos.ServiceReference1.IService1.EndConviteAceitar(System.IAsyncResult result) {
            base.Channel.EndConviteAceitar(result);
        }
        
        private System.IAsyncResult OnBeginConviteAceitar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idConvite = ((int)(inValues[0]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginConviteAceitar(idConvite, callback, asyncState);
        }
        
        private object[] OnEndConviteAceitar(System.IAsyncResult result) {
            ((SisEventos.ServiceReference1.IService1)(this)).EndConviteAceitar(result);
            return null;
        }
        
        private void OnConviteAceitarCompleted(object state) {
            if ((this.ConviteAceitarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConviteAceitarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConviteAceitarAsync(int idConvite) {
            this.ConviteAceitarAsync(idConvite, null);
        }
        
        public void ConviteAceitarAsync(int idConvite, object userState) {
            if ((this.onBeginConviteAceitarDelegate == null)) {
                this.onBeginConviteAceitarDelegate = new BeginOperationDelegate(this.OnBeginConviteAceitar);
            }
            if ((this.onEndConviteAceitarDelegate == null)) {
                this.onEndConviteAceitarDelegate = new EndOperationDelegate(this.OnEndConviteAceitar);
            }
            if ((this.onConviteAceitarCompletedDelegate == null)) {
                this.onConviteAceitarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConviteAceitarCompleted);
            }
            base.InvokeAsync(this.onBeginConviteAceitarDelegate, new object[] {
                        idConvite}, this.onEndConviteAceitarDelegate, this.onConviteAceitarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SisEventos.ServiceReference1.IService1.BeginConviteRecusar(int idConvite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConviteRecusar(idConvite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SisEventos.ServiceReference1.IService1.EndConviteRecusar(System.IAsyncResult result) {
            base.Channel.EndConviteRecusar(result);
        }
        
        private System.IAsyncResult OnBeginConviteRecusar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idConvite = ((int)(inValues[0]));
            return ((SisEventos.ServiceReference1.IService1)(this)).BeginConviteRecusar(idConvite, callback, asyncState);
        }
        
        private object[] OnEndConviteRecusar(System.IAsyncResult result) {
            ((SisEventos.ServiceReference1.IService1)(this)).EndConviteRecusar(result);
            return null;
        }
        
        private void OnConviteRecusarCompleted(object state) {
            if ((this.ConviteRecusarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConviteRecusarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConviteRecusarAsync(int idConvite) {
            this.ConviteRecusarAsync(idConvite, null);
        }
        
        public void ConviteRecusarAsync(int idConvite, object userState) {
            if ((this.onBeginConviteRecusarDelegate == null)) {
                this.onBeginConviteRecusarDelegate = new BeginOperationDelegate(this.OnBeginConviteRecusar);
            }
            if ((this.onEndConviteRecusarDelegate == null)) {
                this.onEndConviteRecusarDelegate = new EndOperationDelegate(this.OnEndConviteRecusar);
            }
            if ((this.onConviteRecusarCompletedDelegate == null)) {
                this.onConviteRecusarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConviteRecusarCompleted);
            }
            base.InvokeAsync(this.onBeginConviteRecusarDelegate, new object[] {
                        idConvite}, this.onEndConviteRecusarDelegate, this.onConviteRecusarCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SisEventos.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }

		internal void EventoAdicionarAsync(string v1, string v2, DateTime now, string phone, float v3, float v4)
		{
			throw new NotImplementedException();
		}

		private class Service1ClientChannel : ChannelBase<SisEventos.ServiceReference1.IService1>, SisEventos.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<SisEventos.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginContatoListar(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ContatoListar", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato> EndContatoListar(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato> _result = ((System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosContato>)(base.EndInvoke("ContatoListar", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEventoListar(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("EventoListar", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> EndEventoListar(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> _result = ((System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento>)(base.EndInvoke("EventoListar", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginContatoAbrir(string numero, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = numero;
                System.IAsyncResult _result = base.BeginInvoke("ContatoAbrir", _args, callback, asyncState);
                return _result;
            }
            
            public SisEventos.ServiceReference1.DadosContato EndContatoAbrir(System.IAsyncResult result) {
                object[] _args = new object[0];
                SisEventos.ServiceReference1.DadosContato _result = ((SisEventos.ServiceReference1.DadosContato)(base.EndInvoke("ContatoAbrir", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginContatoAdicionar(string nome, string numero, string uri, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = nome;
                _args[1] = numero;
                _args[2] = uri;
                System.IAsyncResult _result = base.BeginInvoke("ContatoAdicionar", _args, callback, asyncState);
                return _result;
            }
            
            public void EndContatoAdicionar(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ContatoAdicionar", _args, result);
            }
            
            public System.IAsyncResult BeginContatoAtualizar(string nome, string numero, string uri, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = nome;
                _args[1] = numero;
                _args[2] = uri;
                System.IAsyncResult _result = base.BeginInvoke("ContatoAtualizar", _args, callback, asyncState);
                return _result;
            }
            
            public void EndContatoAtualizar(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ContatoAtualizar", _args, result);
            }
            
            public System.IAsyncResult BeginContatoEventos(string numero, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = numero;
                System.IAsyncResult _result = base.BeginInvoke("ContatoEventos", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> EndContatoEventos(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento> _result = ((System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosEvento>)(base.EndInvoke("ContatoEventos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEventoAbrir(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("EventoAbrir", _args, callback, asyncState);
                return _result;
            }
            
            public SisEventos.ServiceReference1.DadosEvento EndEventoAbrir(System.IAsyncResult result) {
                object[] _args = new object[0];
                SisEventos.ServiceReference1.DadosEvento _result = ((SisEventos.ServiceReference1.DadosEvento)(base.EndInvoke("EventoAbrir", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEventoAdicionar(string nome, string descricao, System.DateTime data, string numero_responsavel, long latitude, long longitude, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = nome;
                _args[1] = descricao;
                _args[2] = data;
                _args[3] = numero_responsavel;
                _args[4] = latitude;
                _args[5] = longitude;
                System.IAsyncResult _result = base.BeginInvoke("EventoAdicionar", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEventoAdicionar(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EventoAdicionar", _args, result);
            }
            
            public System.IAsyncResult BeginEventoAtualizar(int evento_id, string nome, string descricao, System.DateTime data, long latitude, long longitude, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = evento_id;
                _args[1] = nome;
                _args[2] = descricao;
                _args[3] = data;
                _args[4] = latitude;
                _args[5] = longitude;
                System.IAsyncResult _result = base.BeginInvoke("EventoAtualizar", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEventoAtualizar(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EventoAtualizar", _args, result);
            }
            
            public System.IAsyncResult BeginEventoDelete(int evento_id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = evento_id;
                System.IAsyncResult _result = base.BeginInvoke("EventoDelete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEventoDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EventoDelete", _args, result);
            }
            
            public System.IAsyncResult BeginEventoConvidarParticipante(int evento_id, string numero_participante, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = evento_id;
                _args[1] = numero_participante;
                System.IAsyncResult _result = base.BeginInvoke("EventoConvidarParticipante", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEventoConvidarParticipante(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EventoConvidarParticipante", _args, result);
            }
            
            public System.IAsyncResult BeginEventoRemoverParticipante(int evento_id, string numero_participante, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = evento_id;
                _args[1] = numero_participante;
                System.IAsyncResult _result = base.BeginInvoke("EventoRemoverParticipante", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEventoRemoverParticipante(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EventoRemoverParticipante", _args, result);
            }
            
            public System.IAsyncResult BeginConviteAbrir(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("ConviteAbrir", _args, callback, asyncState);
                return _result;
            }
            
            public SisEventos.ServiceReference1.DadosEvento EndConviteAbrir(System.IAsyncResult result) {
                object[] _args = new object[0];
                SisEventos.ServiceReference1.DadosEvento _result = ((SisEventos.ServiceReference1.DadosEvento)(base.EndInvoke("ConviteAbrir", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConviteListar(string numeroContato, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = numeroContato;
                System.IAsyncResult _result = base.BeginInvoke("ConviteListar", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosConvite> EndConviteListar(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosConvite> _result = ((System.Collections.ObjectModel.ObservableCollection<SisEventos.ServiceReference1.DadosConvite>)(base.EndInvoke("ConviteListar", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConviteAceitar(int idConvite, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = idConvite;
                System.IAsyncResult _result = base.BeginInvoke("ConviteAceitar", _args, callback, asyncState);
                return _result;
            }
            
            public void EndConviteAceitar(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ConviteAceitar", _args, result);
            }
            
            public System.IAsyncResult BeginConviteRecusar(int idConvite, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = idConvite;
                System.IAsyncResult _result = base.BeginInvoke("ConviteRecusar", _args, callback, asyncState);
                return _result;
            }
            
            public void EndConviteRecusar(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ConviteRecusar", _args, result);
            }
        }
    }
}
